name: Release to itch.io

on:
  workflow_run:
    workflows: ["godot-ci export"]
    types:
      - completed

env:
  ITCH_USER_NAME: modailun
  ITCH_GAME_NAME: breakout-clone

jobs:
  release-itch:
    name: Release to itch.io
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout the correct commit
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
    - name: Get version from tag
      run: |
        TAGVERSION=$(cat tag_version.txt)
        echo "TAGVERSION=$TAGVERSION" >> $GITHUB_ENV

    # Télécharger les artifacts du workflow de build
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: windows
        path: build/windows
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: linux
        path: build/linux
    - name: Download Web artifact
      uses: actions/download-artifact@v4
      with:
        name: web
        path: build/web

    # Publier sur itch.io
    - name: Publish Windows build to itch.io
      uses: yeslayla/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: windows
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: build/windows
        VERSION: ${{ env.TAGVERSION }}
    - name: Publish Linux build to itch.io
      uses: yeslayla/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: linux
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: build/linux
        VERSION: ${{ env.TAGVERSION }}
    - name: Publish Web build to itch.io
      uses: yeslayla/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: web
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: build/web
        VERSION: ${{ env.TAGVERSION }}